import {
  arbitrum,
  arbitrumSepolia,
  avalanche,
  avalancheFuji,
  base,
  baseSepolia,
  bsc,
  celo,
  fantom,
  fantomTestnet,
  gnosis,
  harmonyOne,
  linea,
  mainnet,
  mantle,
  metis,
  optimism,
  optimismSepolia,
  polygon,
  polygonAmoy,
  polygonZkEvm,
  scroll,
  scrollSepolia,
  sepolia,
  sonic,
  zksync,
  ink,
  inkSepolia,
  soneium,
  bob,
  plasma,
  Chain,
  xLayer,
  megaeth,
  monad,
} from "viem/chains";
import { defineChain } from "viem";

// TODO: replace with viem's own chain once it ships Arc mainnet, 2.45 only has `arcTestnet`.
const arc = defineChain({
  id: 5042,
  name: "Arc",
  nativeCurrency: { name: "USDC", symbol: "USDC", decimals: 18 },
  // TODO: populate once Arc exposes a public rpc.
  rpcUrls: { default: { http: [] } },
  blockExplorers: {
    // TODO: add `apiUrl` once the explorer is no longer gated behind Cloudflare Access.
    default: { name: "Arc Explorer", url: "https://explorer.arc.io" },
  },
  contracts: {
    multicall3: { address: "0xcA11bde05977b3631167028862bE2a173976CA11" },
  },
});

export const ChainId = {
  celo: celo.id,
  mainnet: mainnet.id,
  polygon: polygon.id,
  polygon_amoy: polygonAmoy.id,
  avalanche: avalanche.id,
  avalanche_fuji: avalancheFuji.id,
  arbitrum: arbitrum.id,
  arbitrum_sepolia: arbitrumSepolia.id,
  fantom: fantom.id,
  fantom_testnet: fantomTestnet.id,
  optimism: optimism.id,
  optimism_sepolia: optimismSepolia.id,
  harmony: harmonyOne.id,
  sepolia: sepolia.id,
  scroll: scroll.id,
  scroll_sepolia: scrollSepolia.id,
  sonic: sonic.id,
  mantle: mantle.id,
  metis: metis.id,
  base: base.id,
  base_sepolia: baseSepolia.id,
  bnb: bsc.id,
  gnosis: gnosis.id,
  zkEVM: polygonZkEvm.id,
  zksync: zksync.id,
  linea: linea.id,
  ink: ink.id,
  ink_sepolia: inkSepolia.id,
  soneium: soneium.id,
  bob: bob.id,
  plasma: plasma.id,
  xLayer: xLayer.id,
  megaeth: megaeth.id,
  monad: monad.id,
  arc: arc.id,
} as const;

export const ChainList: Record<valueOf<typeof ChainId>, Chain> = {
  [ChainId.mainnet]: mainnet,
  [ChainId.polygon]: polygon,
  [ChainId.polygon_amoy]: polygonAmoy,
  [ChainId.avalanche]: {
    ...avalanche,
    blockExplorers: {
      default: { url: "https://snowscan.xyz", name: "Snowscan" },
    },
  },
  [ChainId.avalanche_fuji]: {
    ...avalancheFuji,
    blockExplorers: {
      default: { url: "https://testnet.snowscan.xyz", name: "Snowscan Fuji" },
    },
  },
  [ChainId.arbitrum]: arbitrum,
  [ChainId.arbitrum_sepolia]: arbitrumSepolia,
  [ChainId.fantom]: fantom,
  [ChainId.fantom_testnet]: fantomTestnet,
  [ChainId.optimism]: optimism,
  [ChainId.optimism_sepolia]: optimismSepolia,
  [ChainId.harmony]: harmonyOne,
  [ChainId.sepolia]: sepolia,
  [ChainId.scroll]: scroll,
  [ChainId.scroll_sepolia]: scrollSepolia,
  [ChainId.sonic]: sonic,
  [ChainId.mantle]: mantle,
  [ChainId.metis]: metis,
  [ChainId.base]: base,
  [ChainId.base_sepolia]: baseSepolia,
  [ChainId.bnb]: bsc,
  [ChainId.gnosis]: gnosis,
  [ChainId.zkEVM]: polygonZkEvm,
  [ChainId.celo]: celo,
  [ChainId.zksync]: zksync,
  [ChainId.linea]: linea,
  [ChainId.ink]: ink,
  [ChainId.ink_sepolia]: {
    ...inkSepolia,
    blockExplorers: {
      default: {
        url: "https://explorer-sepolia.inkonchain.com/",
        name: "Ink Sepolia",
      },
    },
  },
  [ChainId.soneium]: soneium,
  [ChainId.bob]: bob,
  [ChainId.plasma]: plasma,
  [ChainId.xLayer]: xLayer,
  [ChainId.megaeth]: megaeth,
  [ChainId.monad]: {
    ...monad,
    blockExplorers: {
      default: {
        name: "Monadscan",
        url: "https://monadscan.com",
        apiUrl: "https://api.monadscan.com/api",
      },
    },
  },
  [ChainId.arc]: arc,
};
